# Generated by Django 3.1.1 on 2020-09-12 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='userFrom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userFrom', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='userTo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='userTo', to='auth.user'),
            preserve_default=False,
        ),
    ]
